### ISSUE TITLE
Child pages not pulling through parentPage for the back button

### ISSUE THREAD

**Issue by henocookie** [hippo-digital/communities#9]
Child pages with a `parentPage` variable set do not show the parent page as the backlink at the top of the page.

For example:
https://hippo-digital.github.io/communities/Key-Pride-dates/ should have "Back to Pride" as the backlink and https://hippo-digital.github.io/communities/How-to-refer-to-the-Disabled-community-at-Hippo/ should have "Back to Disabled Community" as the backlink but both have "Back to communities"

**Comment by NickColley** [comment]
I made a breaking change to change parentPage to parent and forgot to update things LOL will fix
